spring.application.name=booking-service

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/feast_booking_db
spring.datasource.username=root
spring.datasource.password=yasar7575M@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always

jwt.secret=MySecretKeyMySecretKeyMySecretKey123456